# ##
# ## EPITECH PROJECT, 2019
# ## Makefile
# ## File description:
# ## Makefile
# ##

# MV			=	mv

# CC			=	g++

# # CXX			=	g++

# CXXFLAGS	=	-Wall -Wextra -std=c++17 

# CPPFLAGS	=	-I$(INCLUDE_DIR)
# # CXXFLAGS	+=	$(INCLUDE)

# LDFLAGS		=	-ldl

# INCLUDE_DIR	=	../includes

# # INCLUDES	=	../lib

# # INCLUDES	+=	../lib/SFML

# # INCLUDES	+=	../lib/NCURSES

# # INCLUDES	+= 	../games/

# NAME		=	arcade

# SRCS		=	main.cpp			\
# 				Core.cpp			\
# 				# ParsingConfig.cpp
			
# OBJ			=	$(SRCS:.cpp=.o)

# $(NAME):	$(OBJ)
# 		# $(RM) ../$(NAME)
# 		$(CC) -o $(NAME) $(OBJ) $(LDFLAGS)
# 		# $(CXX) $(CXXFLAGS) $(LDFLAGS) $(OBJS) -o $(NAME)
# 		$(MV) $(NAME) ..

# all:	$(NAME)

# clean:
# 		$(RM) $(OBJ)

# fclean:		clean
# 		$(RM) $(NAME)

# re:				fclean all

# .PHONY:			all clean fclean re