##
## EPITECH PROJECT, 2019
## Makefile
## File description:
## Makefile
##

all:			# $(SFML)

clean:
				# $(RM) $(SFML_OBJS)

fclean:			clean
				# $(RM) $(SFML)

re:				fclean all

.PHONY:			all clean fclean re