.TH "srcs Directory Reference" 3 "Sun Mar 31 2019" "Version 1.0" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srcs Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCore\&.cpp\fP"
.br
.ti -1c
.RI "file \fBCore\&.hpp\fP"
.br
.ti -1c
.RI "file \fBICore\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBParsingConfig\&.cpp\fP"
.br
.ti -1c
.RI "file \fBParsingConfig\&.hpp\fP"
.br
.in -1c
