.TH "lib/NCURSES Directory Reference" 3 "Sun Mar 31 2019" "Version 1.0" "OOP_arcade_2018" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/NCURSES Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBClassNcurses\&.cpp\fP"
.br
.ti -1c
.RI "file \fBClassNcurses\&.hpp\fP"
.br
.in -1c
