.TH "lib Directory Reference" 3 "Sun Mar 31 2019" "Version 1.0" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBNCURSES\fP"
.br
.ti -1c
.RI "directory \fBSDL\fP"
.br
.ti -1c
.RI "directory \fBSFML\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdlloader\&.hpp\fP"
.br
.ti -1c
.RI "file \fBIGraphic\&.hpp\fP"
.br
.in -1c
