.TH "lib/SFML/AnimatedSprite.hpp" 3 "Sun Mar 31 2019" "Version 1.0" "OOP_arcade_2018" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/SFML/AnimatedSprite.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <SFML/Graphics/RenderTarget\&.hpp>\fP
.br
\fC#include <SFML/System/Time\&.hpp>\fP
.br
\fC#include <SFML/Graphics/Drawable\&.hpp>\fP
.br
\fC#include <SFML/Graphics/Transformable\&.hpp>\fP
.br
\fC#include <SFML/System/Vector2\&.hpp>\fP
.br
\fC#include 'Animation\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAnimatedSprite\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OOP_arcade_2018 from the source code\&.
