.TH "ClassNcurses" 3 "Sun Mar 31 2019" "Version 1.0" "OOP_arcade_2018" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClassNcurses \- Class representing \fBClassNcurses\fP logic\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ClassNcurses\&.hpp>\fP
.PP
Inherits \fBIGraphic\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClassNcurses\fP ()"
.br
.RI "Create the Ncurses window and set the getters at false it also creates subwindows for the menu\&. "
.ti -1c
.RI "\fB~ClassNcurses\fP ()"
.br
.RI "Ncurses Class destructor, just quit the Ncurses\&. "
.ti -1c
.RI "bool \fBrunGraph\fP ()"
.br
.RI "Main fct manage the events, prints and create map\&. "
.ti -1c
.RI "void \fBsetMap\fP (std::shared_ptr< std::vector< std::string >>)"
.br
.RI "Change the char in our _map of textures corresponding to the map\&. "
.ti -1c
.RI "void \fBtranslateKey\fP ()"
.br
.RI "Translate the Ncurses event key to the keycode that the core will understand\&. "
.ti -1c
.RI "void \fBsetIsNewMap\fP (bool)"
.br
.RI "set bool if there's a new map "
.ti -1c
.RI "bool \fBgetIsNewMap\fP (void) const"
.br
.RI "return bool if there's a new map "
.ti -1c
.RI "void \fBsetIsNewKey\fP (bool)"
.br
.RI "set bool if there's a new key press "
.ti -1c
.RI "bool \fBgetIsNewKey\fP (void) const"
.br
.RI "return bool if there's a new key use "
.ti -1c
.RI "void \fBsetLastKey\fP (int)"
.br
.RI "set the int key when a key is press "
.ti -1c
.RI "int \fBgetLastKey\fP (void) const"
.br
.RI "return the int key when a key is press "
.ti -1c
.RI "void \fBsetScore\fP (size_t)"
.br
.RI "set the score when you're playing "
.ti -1c
.RI "size_t \fBgetScore\fP () const"
.br
.RI "return the score when you finish to play "
.ti -1c
.RI "void \fBsetMapTexture\fP ()"
.br
.RI "do nothing "
.ti -1c
.RI "void \fBdisplayGame\fP ()"
.br
.RI "Translate the game's map and print it\&. "
.ti -1c
.RI "void \fBsetPathConfig\fP (std::string) noexcept"
.br
.RI "set when there's a new path config "
.ti -1c
.RI "std::string \fBgetPathConfig\fP () const noexcept"
.br
.RI "return the actual path config "
.ti -1c
.RI "void \fBsetIsNewPathConfig\fP (bool) noexcept"
.br
.RI "set bool if a new path config is set "
.ti -1c
.RI "bool \fBgetIsNewPathConfig\fP () const noexcept"
.br
.RI "return bool if a new path config is set "
.ti -1c
.RI "void \fBbuildMap\fP (std::shared_ptr< std::vector< std::string >>)"
.br
.RI "do nothing "
.ti -1c
.RI "bool \fBgetEvent\fP ()"
.br
.RI "Handle the events of the Ncurses\&. "
.ti -1c
.RI "void \fBdisplayMenu\fP ()"
.br
.RI "display the menu "
.ti -1c
.RI "void \fBdisplayLetters\fP ()"
.br
.RI "Create differents words for the menu\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class representing \fBClassNcurses\fP logic\&. 

This class contains the fonctions that handle the NCURSES 
.PP
Definition at line 32 of file ClassNcurses\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ClassNcurses::ClassNcurses ()"

.PP
Create the Ncurses window and set the getters at false it also creates subwindows for the menu\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP

.PP
Definition at line 17 of file ClassNcurses\&.cpp\&.
.SS "ClassNcurses::~ClassNcurses ()"

.PP
Ncurses Class destructor, just quit the Ncurses\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP

.PP
Definition at line 49 of file ClassNcurses\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void ClassNcurses::buildMap (std::shared_ptr< std::vector< std::string >> map = \fCnullptr\fP)\fC [virtual]\fP"

.PP
do nothing 
.PP
\fBParameters:\fP
.RS 4
\fIstd::shared_ptr<std::vector<std::string>>\fP 
.RE
.PP

.PP
Implements \fBIGraphic\fP\&.
.PP
Definition at line 299 of file ClassNcurses\&.cpp\&.
.SS "void ClassNcurses::displayGame ()"

.PP
Translate the game's map and print it\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP

.PP
Definition at line 156 of file ClassNcurses\&.cpp\&.
.SS "void ClassNcurses::displayLetters ()"

.PP
Create differents words for the menu\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP

.PP
Definition at line 105 of file ClassNcurses\&.cpp\&.
.SS "void ClassNcurses::displayMenu ()"

.PP
display the menu 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP

.PP
Definition at line 61 of file ClassNcurses\&.cpp\&.
.SS "bool ClassNcurses::getEvent ()"

.PP
Handle the events of the Ncurses\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP

.PP
Definition at line 247 of file ClassNcurses\&.cpp\&.
.SS "bool ClassNcurses::getIsNewKey (void) const\fC [virtual]\fP"

.PP
return bool if there's a new key use 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP

.PP
Implements \fBIGraphic\fP\&.
.PP
Definition at line 394 of file ClassNcurses\&.cpp\&.
.SS "bool ClassNcurses::getIsNewMap (void) const\fC [virtual]\fP"

.PP
return bool if there's a new map 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP

.PP
Implements \fBIGraphic\fP\&.
.PP
Definition at line 370 of file ClassNcurses\&.cpp\&.
.SS "bool ClassNcurses::getIsNewPathConfig () const\fC [virtual]\fP, \fC [noexcept]\fP"

.PP
return bool if a new path config is set 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP

.PP
Implements \fBIGraphic\fP\&.
.PP
Definition at line 490 of file ClassNcurses\&.cpp\&.
.SS "int ClassNcurses::getLastKey (void) const\fC [virtual]\fP"

.PP
return the int key when a key is press 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP

.PP
Implements \fBIGraphic\fP\&.
.PP
Definition at line 418 of file ClassNcurses\&.cpp\&.
.SS "std::string ClassNcurses::getPathConfig () const\fC [virtual]\fP, \fC [noexcept]\fP"

.PP
return the actual path config 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP

.PP
Implements \fBIGraphic\fP\&.
.PP
Definition at line 466 of file ClassNcurses\&.cpp\&.
.SS "size_t ClassNcurses::getScore (void) const\fC [virtual]\fP"

.PP
return the score when you finish to play 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP

.PP
Implements \fBIGraphic\fP\&.
.PP
Definition at line 442 of file ClassNcurses\&.cpp\&.
.SS "bool ClassNcurses::runGraph ()\fC [virtual]\fP"

.PP
Main fct manage the events, prints and create map\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP

.PP
Implements \fBIGraphic\fP\&.
.PP
Definition at line 271 of file ClassNcurses\&.cpp\&.
.SS "void ClassNcurses::setIsNewKey (bool NewKey)\fC [virtual]\fP"

.PP
set bool if there's a new key press 
.PP
\fBParameters:\fP
.RS 4
\fIbool\fP 
.RE
.PP

.PP
Implements \fBIGraphic\fP\&.
.PP
Definition at line 382 of file ClassNcurses\&.cpp\&.
.SS "void ClassNcurses::setIsNewMap (bool NewMap)\fC [virtual]\fP"

.PP
set bool if there's a new map 
.PP
\fBParameters:\fP
.RS 4
\fIbool\fP 
.RE
.PP

.PP
Implements \fBIGraphic\fP\&.
.PP
Definition at line 358 of file ClassNcurses\&.cpp\&.
.SS "void ClassNcurses::setIsNewPathConfig (bool isNewPath)\fC [virtual]\fP, \fC [noexcept]\fP"

.PP
set bool if a new path config is set 
.PP
\fBParameters:\fP
.RS 4
\fIbool\fP 
.RE
.PP

.PP
Implements \fBIGraphic\fP\&.
.PP
Definition at line 478 of file ClassNcurses\&.cpp\&.
.SS "void ClassNcurses::setLastKey (int key)\fC [virtual]\fP"

.PP
set the int key when a key is press 
.PP
\fBParameters:\fP
.RS 4
\fIint\fP 
.RE
.PP

.PP
Implements \fBIGraphic\fP\&.
.PP
Definition at line 406 of file ClassNcurses\&.cpp\&.
.SS "void ClassNcurses::setMap (std::shared_ptr< std::vector< std::string >> map)\fC [virtual]\fP"

.PP
Change the char in our _map of textures corresponding to the map\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstd::shared_ptr<std::vector<std::string>>\fP 
.RE
.PP

.PP
Implements \fBIGraphic\fP\&.
.PP
Definition at line 323 of file ClassNcurses\&.cpp\&.
.SS "void ClassNcurses::setMapTexture ()"

.PP
do nothing 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP

.PP
Definition at line 311 of file ClassNcurses\&.cpp\&.
.SS "void ClassNcurses::setPathConfig (std::string path)\fC [virtual]\fP, \fC [noexcept]\fP"

.PP
set when there's a new path config 
.PP
\fBParameters:\fP
.RS 4
\fIstd::string\fP 
.RE
.PP

.PP
Implements \fBIGraphic\fP\&.
.PP
Definition at line 454 of file ClassNcurses\&.cpp\&.
.SS "void ClassNcurses::setScore (size_t score)\fC [virtual]\fP"

.PP
set the score when you're playing 
.PP
\fBParameters:\fP
.RS 4
\fIsize_t\fP 
.RE
.PP

.PP
Implements \fBIGraphic\fP\&.
.PP
Definition at line 430 of file ClassNcurses\&.cpp\&.
.SS "void ClassNcurses::translateKey ()\fC [virtual]\fP"

.PP
Translate the Ncurses event key to the keycode that the core will understand\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP

.PP
Implements \fBIGraphic\fP\&.
.PP
Definition at line 340 of file ClassNcurses\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OOP_arcade_2018 from the source code\&.
