.TH "ClassNcurses" 3 "Sun Mar 31 2019" "Version 1.0" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClassNcurses \- Class representing \fBClassNcurses\fP logic\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ClassNcurses\&.hpp>\fP
.PP
Inherits \fBIGraphic\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClassNcurses\fP ()"
.br
.RI "Create the Ncurses window and set the getters at false it also creates subwindows for the menu\&. "
.ti -1c
.RI "\fB~ClassNcurses\fP ()"
.br
.RI "Ncurses Class destructor, just quit the Ncurses\&. "
.ti -1c
.RI "bool \fBrunGraph\fP ()"
.br
.RI "Handle the events of the Ncurses\&. "
.ti -1c
.RI "void \fBsetMap\fP (std::shared_ptr< std::vector< std::string >>)"
.br
.RI "Change the char in our _map of textures corresponding to the map\&. "
.ti -1c
.RI "void \fBtranslateKey\fP ()"
.br
.RI "Translate the Ncurses event key to the keycode that the core will understand\&. "
.ti -1c
.RI "void \fBsetIsNewMap\fP (bool)"
.br
.ti -1c
.RI "bool \fBgetIsNewMap\fP (void) const"
.br
.ti -1c
.RI "void \fBsetIsNewKey\fP (bool)"
.br
.ti -1c
.RI "bool \fBgetIsNewKey\fP (void) const"
.br
.ti -1c
.RI "void \fBsetLastKey\fP (int)"
.br
.ti -1c
.RI "int \fBgetLastKey\fP (void) const"
.br
.ti -1c
.RI "void \fBsetScore\fP (size_t)"
.br
.ti -1c
.RI "size_t \fBgetScore\fP () const"
.br
.ti -1c
.RI "void \fBsetMapTexture\fP ()"
.br
.ti -1c
.RI "void \fBdisplayGame\fP ()"
.br
.ti -1c
.RI "void \fBsetPathConfig\fP (std::string) noexcept"
.br
.ti -1c
.RI "std::string \fBgetPathConfig\fP () const noexcept"
.br
.ti -1c
.RI "void \fBsetIsNewPathConfig\fP (bool) noexcept"
.br
.ti -1c
.RI "bool \fBgetIsNewPathConfig\fP () const noexcept"
.br
.ti -1c
.RI "void \fBbuildMap\fP (std::shared_ptr< std::vector< std::string >>)"
.br
.ti -1c
.RI "bool \fBgetEvent\fP ()"
.br
.RI "Handle the events of the Ncurses\&. "
.ti -1c
.RI "void \fBdisplayMenu\fP ()"
.br
.ti -1c
.RI "void \fBdisplayLetters\fP ()"
.br
.ti -1c
.RI "int \fBget_input\fP ()"
.br
.RI "Handle the inputs of the user\&. "
.ti -1c
.RI "std::string \fBget_string\fP ()"
.br
.ti -1c
.RI "char \fBtranslate_for_menu\fP (int)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class representing \fBClassNcurses\fP logic\&. 

This class contains the fonctions that handle the NCURSES 
.PP
Definition at line 32 of file ClassNcurses\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ClassNcurses::ClassNcurses ()"

.PP
Create the Ncurses window and set the getters at false it also creates subwindows for the menu\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP

.PP
Definition at line 17 of file ClassNcurses\&.cpp\&.
.SS "ClassNcurses::~ClassNcurses ()"

.PP
Ncurses Class destructor, just quit the Ncurses\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP

.PP
Definition at line 47 of file ClassNcurses\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void ClassNcurses::buildMap (std::shared_ptr< std::vector< std::string >> map = \fCnullptr\fP)\fC [virtual]\fP"

.PP
Implements \fBIGraphic\fP\&.
.PP
Definition at line 289 of file ClassNcurses\&.cpp\&.
.SS "void ClassNcurses::displayGame ()"

.PP
Definition at line 121 of file ClassNcurses\&.cpp\&.
.SS "void ClassNcurses::displayLetters ()"

.PP
Definition at line 77 of file ClassNcurses\&.cpp\&.
.SS "void ClassNcurses::displayMenu ()"

.PP
Definition at line 52 of file ClassNcurses\&.cpp\&.
.SS "int ClassNcurses::get_input ()"

.PP
Handle the inputs of the user\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP

.PP
Definition at line 234 of file ClassNcurses\&.cpp\&.
.SS "std::string ClassNcurses::get_string ()"

.PP
Definition at line 250 of file ClassNcurses\&.cpp\&.
.SS "bool ClassNcurses::getEvent ()"

.PP
Handle the events of the Ncurses\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP

.PP
Definition at line 211 of file ClassNcurses\&.cpp\&.
.SS "bool ClassNcurses::getIsNewKey (void) const\fC [virtual]\fP"

.PP
Implements \fBIGraphic\fP\&.
.PP
Definition at line 442 of file ClassNcurses\&.cpp\&.
.SS "bool ClassNcurses::getIsNewMap (void) const\fC [virtual]\fP"

.PP
Implements \fBIGraphic\fP\&.
.PP
Definition at line 432 of file ClassNcurses\&.cpp\&.
.SS "bool ClassNcurses::getIsNewPathConfig () const\fC [virtual]\fP, \fC [noexcept]\fP"

.PP
Implements \fBIGraphic\fP\&.
.PP
Definition at line 482 of file ClassNcurses\&.cpp\&.
.SS "int ClassNcurses::getLastKey (void) const\fC [virtual]\fP"

.PP
Implements \fBIGraphic\fP\&.
.PP
Definition at line 452 of file ClassNcurses\&.cpp\&.
.SS "std::string ClassNcurses::getPathConfig () const\fC [virtual]\fP, \fC [noexcept]\fP"

.PP
Implements \fBIGraphic\fP\&.
.PP
Definition at line 472 of file ClassNcurses\&.cpp\&.
.SS "size_t ClassNcurses::getScore (void) const\fC [virtual]\fP"

.PP
Implements \fBIGraphic\fP\&.
.PP
Definition at line 462 of file ClassNcurses\&.cpp\&.
.SS "bool ClassNcurses::runGraph ()\fC [virtual]\fP"

.PP
Handle the events of the Ncurses\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP

.PP
Implements \fBIGraphic\fP\&.
.PP
Definition at line 268 of file ClassNcurses\&.cpp\&.
.SS "void ClassNcurses::setIsNewKey (bool NewKey)\fC [virtual]\fP"

.PP
Implements \fBIGraphic\fP\&.
.PP
Definition at line 437 of file ClassNcurses\&.cpp\&.
.SS "void ClassNcurses::setIsNewMap (bool NewMap)\fC [virtual]\fP"

.PP
Implements \fBIGraphic\fP\&.
.PP
Definition at line 427 of file ClassNcurses\&.cpp\&.
.SS "void ClassNcurses::setIsNewPathConfig (bool isNewPath)\fC [virtual]\fP, \fC [noexcept]\fP"

.PP
Implements \fBIGraphic\fP\&.
.PP
Definition at line 477 of file ClassNcurses\&.cpp\&.
.SS "void ClassNcurses::setLastKey (int key)\fC [virtual]\fP"

.PP
Implements \fBIGraphic\fP\&.
.PP
Definition at line 447 of file ClassNcurses\&.cpp\&.
.SS "void ClassNcurses::setMap (std::shared_ptr< std::vector< std::string >> map)\fC [virtual]\fP"

.PP
Change the char in our _map of textures corresponding to the map\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstd::shared_ptr<std::vector<std::string>>\fP map 
.RE
.PP

.PP
Implements \fBIGraphic\fP\&.
.PP
Definition at line 398 of file ClassNcurses\&.cpp\&.
.SS "void ClassNcurses::setMapTexture ()"

.PP
Definition at line 294 of file ClassNcurses\&.cpp\&.
.SS "void ClassNcurses::setPathConfig (std::string path)\fC [virtual]\fP, \fC [noexcept]\fP"

.PP
Implements \fBIGraphic\fP\&.
.PP
Definition at line 467 of file ClassNcurses\&.cpp\&.
.SS "void ClassNcurses::setScore (size_t score)\fC [virtual]\fP"

.PP
Implements \fBIGraphic\fP\&.
.PP
Definition at line 457 of file ClassNcurses\&.cpp\&.
.SS "char ClassNcurses::translate_for_menu (int nb)"

.PP
Definition at line 255 of file ClassNcurses\&.cpp\&.
.SS "void ClassNcurses::translateKey ()\fC [virtual]\fP"

.PP
Translate the Ncurses event key to the keycode that the core will understand\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP

.PP
Implements \fBIGraphic\fP\&.
.PP
Definition at line 414 of file ClassNcurses\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Arcade from the source code\&.
