.TH "lib/SDL/ClassSDL.cpp" 3 "Sun Mar 31 2019" "Version 1.0" "OOP_arcade_2018" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/SDL/ClassSDL.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'ClassSDL\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBIGraphic\fP * \fBentryPoint\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBIGraphic\fP* entryPoint (void)"

.PP
Definition at line 267 of file ClassSDL\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OOP_arcade_2018 from the source code\&.
