.TH "lib/NCURSES/ClassNcurses.hpp" 3 "Sun Mar 31 2019" "Version 1.0" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/NCURSES/ClassNcurses.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <ncurses\&.h>\fP
.br
\fC#include 'IGraphic\&.hpp'\fP
.br
\fC#include '\&.\&./srcs/ParsingConfig\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBClassNcurses\fP"
.br
.RI "Class representing \fBClassNcurses\fP logic\&. "
.ti -1c
.RI "struct \fBKeyNcurses\fP"
.br
.RI "This Structure contains Keys input translation\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBGraphics\fP { \fBNOTHING\fP = '0', \fBWALL\fP = '1', \fBPOINT\fP = '2', \fBPLAYER\fP = '3', \fBGHOST\fP = '4', \fBBONUS\fP = '5', \fBSDL\fP = '6', \fBSFML\fP = '7', \fBNCURSES\fP = '8', \fBNOTHING\fP = '0', \fBWALL\fP = '1', \fBPOINT\fP = '2', \fBPLAYER\fP = '3', \fBENEMY\fP = '4', \fBBONUS\fP = '5', \fBSDL\fP = '6', \fBSFML\fP = '7', \fBNCURSES\fP = '8', \fBNOTHING\fP = '0', \fBWALL\fP = '1', \fBPOINT\fP = '2', \fBPLAYER\fP = '3', \fBENEMY\fP = '4', \fBBONUS\fP = '5', \fBSDL\fP = '6', \fBSFML\fP = '7', \fBNCURSES\fP = '8' }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBGraphics\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINOTHING \fP\fP
.TP
\fB\fIWALL \fP\fP
.TP
\fB\fIPOINT \fP\fP
.TP
\fB\fIPLAYER \fP\fP
.TP
\fB\fIGHOST \fP\fP
.TP
\fB\fIBONUS \fP\fP
.TP
\fB\fISDL \fP\fP
.TP
\fB\fISFML \fP\fP
.TP
\fB\fINCURSES \fP\fP
.TP
\fB\fINOTHING \fP\fP
.TP
\fB\fIWALL \fP\fP
.TP
\fB\fIPOINT \fP\fP
.TP
\fB\fIPLAYER \fP\fP
.TP
\fB\fIENEMY \fP\fP
.TP
\fB\fIBONUS \fP\fP
.TP
\fB\fISDL \fP\fP
.TP
\fB\fISFML \fP\fP
.TP
\fB\fINCURSES \fP\fP
.TP
\fB\fINOTHING \fP\fP
.TP
\fB\fIWALL \fP\fP
.TP
\fB\fIPOINT \fP\fP
.TP
\fB\fIPLAYER \fP\fP
.TP
\fB\fIENEMY \fP\fP
.TP
\fB\fIBONUS \fP\fP
.TP
\fB\fISDL \fP\fP
.TP
\fB\fISFML \fP\fP
.TP
\fB\fINCURSES \fP\fP
.PP
Definition at line 14 of file ClassNcurses\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Arcade from the source code\&.
