.TH "srcs/Core.hpp" 3 "Sun Mar 31 2019" "Version 1.0" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srcs/Core.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <chrono>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <thread>\fP
.br
\fC#include 'ParsingConfig\&.hpp'\fP
.br
\fC#include 'dlloader\&.hpp'\fP
.br
\fC#include 'IGraphic\&.hpp'\fP
.br
\fC#include 'IGame\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCore\fP"
.br
.RI "Class representing the core\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBCommands\fP { \fBNCURSES\fP = 9, \fBSFML\fP = 10, \fBSDL\fP = 11, \fBENTER\fP = 40 }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBCommands\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINCURSES \fP\fP
.TP
\fB\fISFML \fP\fP
.TP
\fB\fISDL \fP\fP
.TP
\fB\fIENTER \fP\fP
.PP
Definition at line 19 of file Core\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Arcade from the source code\&.
