.TH "DataParsingConfig" 3 "Sun Mar 31 2019" "Version 1.0" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataParsingConfig \- This Structure contains all the informations about our sprites, the path to the \&.bmp, it size in x and y, the ncurses character, the key in the eventuallity it's interactive and the name of the sprite\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ParsingConfig\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBpath\fP"
.br
.ti -1c
.RI "int \fBsizeX\fP"
.br
.ti -1c
.RI "int \fBsizeY\fP"
.br
.ti -1c
.RI "std::string \fBcaractere\fP"
.br
.ti -1c
.RI "int \fBlaunchKey\fP"
.br
.ti -1c
.RI "std::string \fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This Structure contains all the informations about our sprites, the path to the \&.bmp, it size in x and y, the ncurses character, the key in the eventuallity it's interactive and the name of the sprite\&. 
.PP
Definition at line 19 of file ParsingConfig\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string DataParsingConfig::caractere"

.PP
Definition at line 23 of file ParsingConfig\&.hpp\&.
.SS "int DataParsingConfig::launchKey"

.PP
Definition at line 24 of file ParsingConfig\&.hpp\&.
.SS "std::string DataParsingConfig::name"

.PP
Definition at line 25 of file ParsingConfig\&.hpp\&.
.SS "std::string DataParsingConfig::path"

.PP
Definition at line 20 of file ParsingConfig\&.hpp\&.
.SS "int DataParsingConfig::sizeX"

.PP
Definition at line 21 of file ParsingConfig\&.hpp\&.
.SS "int DataParsingConfig::sizeY"

.PP
Definition at line 22 of file ParsingConfig\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Arcade from the source code\&.
