.TH "DLLoader< T >" 3 "Sun Mar 31 2019" "Version 1.0" "OOP_arcade_2018" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DLLoader< T > \- Class representing \fBDLLoader\fP's logic\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dlloader\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDLLoader\fP (std::string lib_path)"
.br
.ti -1c
.RI "\fB~DLLoader\fP ()"
.br
.ti -1c
.RI "T \fBgetInstance\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class DLLoader< T >"
Class representing \fBDLLoader\fP's logic\&. 

This class contains the fonctions that will return the entrypoints of our libraries and games 
.PP
Definition at line 20 of file dlloader\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBDLLoader\fP< T >::\fBDLLoader\fP (std::string lib_path)\fC [inline]\fP"

.PP
Definition at line 23 of file dlloader\&.hpp\&.
.SS "template<typename T > \fBDLLoader\fP< T >::~\fBDLLoader\fP ()\fC [inline]\fP"

.PP
Definition at line 32 of file dlloader\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > T \fBDLLoader\fP< T >::getInstance () const\fC [inline]\fP"

.PP
Definition at line 39 of file dlloader\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OOP_arcade_2018 from the source code\&.
