.TH "games/pacman/Entity.hpp" 3 "Sun Mar 31 2019" "Version 1.0" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
games/pacman/Entity.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <map>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBs_pos\fP"
.br
.ti -1c
.RI "class \fBEntity\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBs_pos\fP \fBt_pos\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBMove\fP { \fBRIGHT\fP = 3, \fBLEFT\fP = 16, \fBDOWN\fP = 18, \fBUP\fP = 25 }"
.br
.ti -1c
.RI "enum \fBPacmanObjs\fP { \fBNOTHING\fP = '0', \fBWALL\fP = '1', \fBPOINT\fP = '2', \fBPLAYER\fP = '3', \fBENEMY\fP = '4', \fBBONUS\fP = '5' }"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBs_pos\fP    \fBt_pos\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBMove\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIRIGHT \fP\fP
.TP
\fB\fILEFT \fP\fP
.TP
\fB\fIDOWN \fP\fP
.TP
\fB\fIUP \fP\fP
.PP
Definition at line 17 of file Entity\&.hpp\&.
.SS "enum \fBPacmanObjs\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINOTHING \fP\fP
.TP
\fB\fIWALL \fP\fP
.TP
\fB\fIPOINT \fP\fP
.TP
\fB\fIPLAYER \fP\fP
.TP
\fB\fIENEMY \fP\fP
.TP
\fB\fIBONUS \fP\fP
.PP
Definition at line 25 of file Entity\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Arcade from the source code\&.
