.TH "ICore" 3 "Sun Mar 31 2019" "Version 1.0" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ICore
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ICore\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~ICore\fP ()=default"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file ICore\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ICore::~ICore ()\fC [virtual]\fP, \fC [default]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Arcade from the source code\&.
