.TH "includes/IGraphic.hpp" 3 "Sun Mar 31 2019" "Version 1.0" "OOP_arcade_2018" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/IGraphic.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIGraphic\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSCREEN_HEIGHT\fP   1000"
.br
.ti -1c
.RI "#define \fBSCREEN_WIDTH\fP   1000"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SCREEN_HEIGHT   1000"

.PP
Definition at line 16 of file IGraphic\&.hpp\&.
.SS "#define SCREEN_WIDTH   1000"

.PP
Definition at line 17 of file IGraphic\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OOP_arcade_2018 from the source code\&.
