.TH "KeySFML" 3 "Sun Mar 31 2019" "Version 1.0" "OOP_arcade_2018" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KeySFML \- This Structure contains Keys input translation\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ClassSFML\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcode_lib\fP"
.br
.ti -1c
.RI "int \fBcode_core\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This Structure contains Keys input translation\&. 
.PP
Definition at line 94 of file ClassSFML\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int KeySFML::code_core"

.PP
Definition at line 96 of file ClassSFML\&.hpp\&.
.SS "int KeySFML::code_lib"

.PP
Definition at line 95 of file ClassSFML\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OOP_arcade_2018 from the source code\&.
