.TH "KeySFML" 3 "Sun Mar 31 2019" "Version 1.0" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KeySFML
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ClassSFML\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcode_lib\fP"
.br
.ti -1c
.RI "int \fBcode_core\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 86 of file ClassSFML\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int KeySFML::code_core"

.PP
Definition at line 88 of file ClassSFML\&.hpp\&.
.SS "int KeySFML::code_lib"

.PP
Definition at line 87 of file ClassSFML\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Arcade from the source code\&.
