.TH "srcs/main.cpp" 3 "Sun Mar 31 2019" "Version 1.0" "OOP_arcade_2018" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srcs/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <thread>\fP
.br
\fC#include <chrono>\fP
.br
\fC#include 'Core\&.hpp'\fP
.br
\fC#include 'IGame\&.hpp'\fP
.br
\fC#include 'IGraphic\&.hpp'\fP
.br
\fC#include 'dlloader\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int ac, char **av, char **env)"
.br
.RI "Briefly checks for errors and launch the core\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int ac, char ** av, char ** env)"

.PP
Briefly checks for errors and launch the core\&. 
.PP
\fBParameters:\fP
.RS 4
\fIint\fP ac, char **av and the char **env variables 
.RE
.PP
\fBReturns:\fP
.RS 4
0 if everything went ok or 84 is case of errors 
.RE
.PP

.PP
Definition at line 37 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OOP_arcade_2018 from the source code\&.
