.TH "Pacman" 3 "Sun Mar 31 2019" "Version 1.0" "OOP_arcade_2018" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pacman \- Class representing \fBPacman\fP logic\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Pacman\&.hpp>\fP
.PP
Inherits \fBIGame\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPacman\fP ()"
.br
.RI "Create the \fBPacman\fP game\&. "
.ti -1c
.RI "\fB~Pacman\fP ()"
.br
.RI "\fBPacman\fP Class destructor\&. "
.ti -1c
.RI "bool \fBrunGame\fP ()"
.br
.RI "Set the clock of the game and handle the logic\&. "
.ti -1c
.RI "void \fBsetMap\fP (std::shared_ptr< std::vector< std::string >>)"
.br
.ti -1c
.RI "std::shared_ptr< std::vector< std::string > > \fBgetMap\fP (void) const"
.br
.ti -1c
.RI "void \fBreadMap\fP (void)"
.br
.RI "Read the map\&. "
.ti -1c
.RI "void \fBsetIsNewMap\fP (bool)"
.br
.ti -1c
.RI "bool \fBgetIsNewMap\fP (void) const"
.br
.ti -1c
.RI "void \fBsetIsNewKey\fP (bool)"
.br
.ti -1c
.RI "bool \fBgetIsNewKey\fP (void) const"
.br
.ti -1c
.RI "void \fBsetLastKey\fP (int)"
.br
.ti -1c
.RI "int \fBgetLastKey\fP (void) const"
.br
.ti -1c
.RI "void \fBsetScore\fP (size_t)"
.br
.ti -1c
.RI "size_t \fBgetScore\fP () const"
.br
.ti -1c
.RI "void \fBsetBonus\fP (bool)"
.br
.ti -1c
.RI "bool \fBgetBonus\fP (void) const"
.br
.ti -1c
.RI "void \fBsetMove\fP (\fBMove\fP)"
.br
.ti -1c
.RI "\fBMove\fP \fBgetMove\fP () const"
.br
.ti -1c
.RI "bool \fBcanMove\fP () const"
.br
.ti -1c
.RI "void \fBmoveDown\fP (void)"
.br
.ti -1c
.RI "void \fBmoveLeft\fP (void)"
.br
.ti -1c
.RI "void \fBmoveRight\fP (void)"
.br
.ti -1c
.RI "void \fBmoveUp\fP (void)"
.br
.ti -1c
.RI "void \fBcheckNextCase\fP (char)"
.br
.ti -1c
.RI "const std::string \fBgetPathConfig\fP () const noexcept"
.br
.ti -1c
.RI "const std::string \fBgetPathMap\fP () const noexcept"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class representing \fBPacman\fP logic\&. 

This class contains the fonctions that handle the \fBPacman\fP 
.PP
Definition at line 19 of file Pacman\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Pacman::Pacman ()"

.PP
Create the \fBPacman\fP game\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP

.PP
Definition at line 17 of file Pacman\&.cpp\&.
.SS "Pacman::~Pacman ()"

.PP
\fBPacman\fP Class destructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP

.PP
Definition at line 43 of file Pacman\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Pacman::canMove () const"

.SS "void Pacman::checkNextCase (char)"

.SS "bool Pacman::getBonus (void) const"

.SS "bool Pacman::getIsNewKey (void) const\fC [virtual]\fP"

.PP
Implements \fBIGame\fP\&.
.PP
Definition at line 159 of file Pacman\&.cpp\&.
.SS "bool Pacman::getIsNewMap (void) const\fC [virtual]\fP"

.PP
Implements \fBIGame\fP\&.
.PP
Definition at line 149 of file Pacman\&.cpp\&.
.SS "int Pacman::getLastKey (void) const\fC [virtual]\fP"

.PP
Implements \fBIGame\fP\&.
.PP
Definition at line 169 of file Pacman\&.cpp\&.
.SS "std::shared_ptr< std::vector< std::string > > Pacman::getMap (void) const\fC [virtual]\fP"

.PP
Implements \fBIGame\fP\&.
.PP
Definition at line 139 of file Pacman\&.cpp\&.
.SS "\fBMove\fP Pacman::getMove () const"

.PP
Definition at line 200 of file Pacman\&.cpp\&.
.SS "const std::string Pacman::getPathConfig () const\fC [virtual]\fP, \fC [noexcept]\fP"

.PP
Implements \fBIGame\fP\&.
.PP
Definition at line 184 of file Pacman\&.cpp\&.
.SS "const std::string Pacman::getPathMap () const\fC [virtual]\fP, \fC [noexcept]\fP"

.PP
Implements \fBIGame\fP\&.
.PP
Definition at line 189 of file Pacman\&.cpp\&.
.SS "size_t Pacman::getScore (void) const\fC [virtual]\fP"

.PP
Implements \fBIGame\fP\&.
.PP
Definition at line 179 of file Pacman\&.cpp\&.
.SS "void Pacman::moveDown (void)"

.SS "void Pacman::moveLeft (void)"

.SS "void Pacman::moveRight (void)"

.SS "void Pacman::moveUp (void)"

.SS "void Pacman::readMap (void)"

.PP
Read the map\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP

.PP
Definition at line 104 of file Pacman\&.cpp\&.
.SS "bool Pacman::runGame ()\fC [virtual]\fP"

.PP
Set the clock of the game and handle the logic\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP

.PP
Implements \fBIGame\fP\&.
.PP
Definition at line 55 of file Pacman\&.cpp\&.
.SS "void Pacman::setBonus (bool)"

.SS "void Pacman::setIsNewKey (bool isNewKey)\fC [virtual]\fP"

.PP
Implements \fBIGame\fP\&.
.PP
Definition at line 154 of file Pacman\&.cpp\&.
.SS "void Pacman::setIsNewMap (bool map)\fC [virtual]\fP"

.PP
Implements \fBIGame\fP\&.
.PP
Definition at line 144 of file Pacman\&.cpp\&.
.SS "void Pacman::setLastKey (int key)\fC [virtual]\fP"

.PP
Implements \fBIGame\fP\&.
.PP
Definition at line 164 of file Pacman\&.cpp\&.
.SS "void Pacman::setMap (std::shared_ptr< std::vector< std::string >> map)\fC [virtual]\fP"

.PP
Implements \fBIGame\fP\&.
.PP
Definition at line 134 of file Pacman\&.cpp\&.
.SS "void Pacman::setMove (\fBMove\fP lastMove)"

.PP
Definition at line 194 of file Pacman\&.cpp\&.
.SS "void Pacman::setScore (size_t score)\fC [virtual]\fP"

.PP
Implements \fBIGame\fP\&.
.PP
Definition at line 174 of file Pacman\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OOP_arcade_2018 from the source code\&.
