.TH "games/pacman/Pacman.cpp" 3 "Sun Mar 31 2019" "Version 1.0" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
games/pacman/Pacman.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Pacman\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBIGame\fP * \fBentryPoint\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBIGame\fP* entryPoint (void)"

.PP
Definition at line 180 of file Pacman\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Arcade from the source code\&.
