.TH "games/pacman/Pacman.hpp" 3 "Sun Mar 31 2019" "Version 1.0" "OOP_arcade_2018" \" -*- nroff -*-
.ad l
.nh
.SH NAME
games/pacman/Pacman.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Entity\&.hpp'\fP
.br
\fC#include 'IGame\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPacman\fP"
.br
.RI "Class representing \fBPacman\fP logic\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OOP_arcade_2018 from the source code\&.
