.TH "srcs/ParsingConfig.hpp" 3 "Sun Mar 31 2019" "Version 1.0" "OOP_arcade_2018" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srcs/ParsingConfig.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBDataParsingConfig\fP"
.br
.RI "This Structure contains all the informations about our sprites, the path to the \&.bmp, it size in x and y, the ncurses character, the key in the eventuallity it's interactive and the name of the sprite\&. "
.ti -1c
.RI "class \fBParsingConfig\fP"
.br
.RI "Class representing parsing logic\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OOP_arcade_2018 from the source code\&.
