.TH "s_KeySdl" 3 "Sun Mar 31 2019" "Version 1.0" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_KeySdl \- This Structure contains Keys input translation\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ClassSDL\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcode_lib\fP"
.br
.ti -1c
.RI "int \fBcode_core\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This Structure contains Keys input translation\&. 
.PP
Definition at line 87 of file ClassSDL\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int s_KeySdl::code_core"

.PP
Definition at line 89 of file ClassSDL\&.hpp\&.
.SS "int s_KeySdl::code_lib"

.PP
Definition at line 88 of file ClassSDL\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Arcade from the source code\&.
