.TH "s_pos" 3 "Sun Mar 31 2019" "Version 1.0" "OOP_arcade_2018" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_pos
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Entity\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBx\fP"
.br
.ti -1c
.RI "size_t \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file Entity\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "size_t s_pos::x"

.PP
Definition at line 35 of file Entity\&.hpp\&.
.SS "size_t s_pos::y"

.PP
Definition at line 36 of file Entity\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OOP_arcade_2018 from the source code\&.
