.TH "tests/tests_SDL.cpp" 3 "Sun Mar 31 2019" "Version 1.0" "OOP_arcade_2018" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/tests_SDL.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <criterion/criterion\&.h>\fP
.br
\fC#include <criterion/redirect\&.h>\fP
.br
\fC#include 'ClassSDL\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTest\fP (tests_SDL, test_getIsNewKeyIsTrue)"
.br
.ti -1c
.RI "\fBTest\fP (tests_SDL, test_getIsNewKeyIsFalse)"
.br
.ti -1c
.RI "\fBTest\fP (tests_SDL, test_getIsNewMapIsTrue)"
.br
.ti -1c
.RI "\fBTest\fP (tests_SDL, test_getIsNewMapIsFalse)"
.br
.ti -1c
.RI "\fBTest\fP (tests_SDL, test_getLastKeyIsTrue)"
.br
.ti -1c
.RI "\fBTest\fP (tests_SDL, test_getLastKeyIsFalse)"
.br
.ti -1c
.RI "\fBTest\fP (tests_SDL, test_getScore)"
.br
.ti -1c
.RI "\fBTest\fP (tests_SDL, test_getPathConfig)"
.br
.ti -1c
.RI "\fBTest\fP (tests_SDL, test_getIsNewPathConfigIsTrue)"
.br
.ti -1c
.RI "\fBTest\fP (tests_SDL, test_getIsNewPathConfigIsFalse)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "Test (tests_SDL, test_getIsNewKeyIsTrue)"

.PP
Definition at line 12 of file tests_SDL\&.cpp\&.
.SS "Test (tests_SDL, test_getIsNewKeyIsFalse)"

.PP
Definition at line 20 of file tests_SDL\&.cpp\&.
.SS "Test (tests_SDL, test_getIsNewMapIsTrue)"

.PP
Definition at line 28 of file tests_SDL\&.cpp\&.
.SS "Test (tests_SDL, test_getIsNewMapIsFalse)"

.PP
Definition at line 36 of file tests_SDL\&.cpp\&.
.SS "Test (tests_SDL, test_getLastKeyIsTrue)"

.PP
Definition at line 43 of file tests_SDL\&.cpp\&.
.SS "Test (tests_SDL, test_getLastKeyIsFalse)"

.PP
Definition at line 51 of file tests_SDL\&.cpp\&.
.SS "Test (tests_SDL, test_getScore)"

.PP
Definition at line 59 of file tests_SDL\&.cpp\&.
.SS "Test (tests_SDL, test_getPathConfig)"

.PP
Definition at line 71 of file tests_SDL\&.cpp\&.
.SS "Test (tests_SDL, test_getIsNewPathConfigIsTrue)"

.PP
Definition at line 83 of file tests_SDL\&.cpp\&.
.SS "Test (tests_SDL, test_getIsNewPathConfigIsFalse)"

.PP
Definition at line 91 of file tests_SDL\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OOP_arcade_2018 from the source code\&.
